# Site settings
title: Portfolio - devAlex
description: This is my portfolio
# User settings
username: Alex
user_description: Tech enthusiast passionate in codes.
user_title: Front-end Developer
email: alexsaji111@gmail.com
twitter_username: AlexSajiGeorge
github_username:  alexsaji111
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
